---

- name: Install prerequisite packages
  ansible.builtin.apt:
    name:
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
    state: latest
    update_cache: true
  become: true

- name: Add key for Docker repository
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: true

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: https://download.docker.com/linux/ubuntu focal stable
    state: present
  become: true

- name: Install Docker packages
  ansible.builtin.apt:
    name:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    state: latest
    update_cache: true
  become: true