---

- name: Install prerequisite packages
  ansible.builtin.apt:
    name:
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
    - python3-pip
    state: latest
    update_cache: true
  become: true
  when: ansible_facts['os_family'] == "Debian"

- name: Install prerequisite Python packages
  ansible.builtin.pip:
    name:
      - docker
      - docker-compose

- name: Add key for Docker repository
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: true
  when: ansible_facts['os_family'] == "Debian"

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present
  become: true
  when: ansible_facts['os_family'] == "Debian"

- name: Install Docker packages
  ansible.builtin.apt:
    name:
    - docker-ce
    - docker-ce-cli
    - docker-compose
    - containerd.io
    state: latest
    update_cache: true
  become: true
  when: ansible_facts['os_family'] == "Debian"